# Generated by Django 3.1.5 on 2021-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='event_place',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
