# Generated by Django 3.1.5 on 2021-02-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210210_1131'),
        ('events', '0002_userpost_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.accountdetail'),
        ),
    ]
