# Generated by Django 3.1.5 on 2021-01-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
