# Generated by Django 3.1.5 on 2021-01-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accountdetail_paid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='stripe_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
