# Generated by Django 3.1.5 on 2021-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210215_1252'),
        ('events', '0006_auto_20210215_1252'),
        ('core', '0004_auto_20210210_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='AccountDetail',
        ),
    ]
